import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service",
};

export default function TermsPage() {
  return (
    <main className="mx-auto max-w-3xl px-6 py-24 text-ct-text-primary">
      <h1 className="text-3xl font-bold tracking-tight sm:text-4xl">
        Terms of Service
      </h1>
      <p className="mt-2 text-sm text-ct-text-tertiary">
        Last updated: April 2026
      </p>
      <p className="mt-4 rounded-lg border border-ct-border-subtle bg-ct-surface p-4 text-sm text-ct-text-secondary">
        <strong>Draft notice:</strong> This is a placeholder. These terms are
        not legal advice and have not been reviewed by counsel.
      </p>

      <section className="mt-12 space-y-10 text-sm leading-relaxed text-ct-text-secondary">
        <div>
          <h2 className="text-lg font-semibold text-ct-text-primary">
            1. Acceptance of Terms
          </h2>
          <p className="mt-2">
            By accessing or using CosmicTasha, you agree to be bound by these
            Terms of Service. If you do not agree, you may not use the service.
            We reserve the right to update these terms at any time with
            reasonable notice.
          </p>
        </div>

        <div>
          <h2 className="text-lg font-semibold text-ct-text-primary">
            2. Description of Service
          </h2>
          <p className="mt-2">
            CosmicTasha provides AI-assisted SOC 2 compliance document
            generation, gap analysis, and readiness scoring. The service
            includes a guided intake flow, automated policy drafting, and
            human-in-the-loop review capabilities.
          </p>
        </div>

        <div>
          <h2 className="text-lg font-semibold text-ct-text-primary">
            3. User Responsibilities
          </h2>
          <p className="mt-2">
            You are responsible for the accuracy of the information you provide
            during the intake process. You agree not to misuse the service, and
            to comply with all applicable laws and regulations when using
            generated documents.
          </p>
        </div>

        <div>
          <h2 className="text-lg font-semibold text-ct-text-primary">
            4. AI-Generated Content Disclaimer
          </h2>
          <p className="mt-2">
            Documents generated by CosmicTasha are AI-assisted drafts. You are
            responsible for reviewing and approving all content before use.
            Generated documents do not constitute legal, security, or
            compliance advice. We recommend engaging qualified professionals to
            review all outputs before submission to auditors.
          </p>
        </div>

        <div>
          <h2 className="text-lg font-semibold text-ct-text-primary">
            5. Data Handling
          </h2>
          <p className="mt-2">
            We process your data solely to provide the service. Intake data is
            used for document generation and gap analysis. See our Privacy
            Policy for full details on data collection, storage, and retention
            practices.
          </p>
        </div>

        <div>
          <h2 className="text-lg font-semibold text-ct-text-primary">
            6. Limitation of Liability
          </h2>
          <p className="mt-2">
            To the maximum extent permitted by law, CosmicTasha and its
            affiliates shall not be liable for any indirect, incidental, or
            consequential damages arising from your use of the service. Our
            total liability is limited to the amount you paid for the service
            in the 12 months preceding the claim.
          </p>
        </div>

        <div>
          <h2 className="text-lg font-semibold text-ct-text-primary">
            7. Contact
          </h2>
          <p className="mt-2">
            For questions about these terms, contact us at{" "}
            <a
              href="mailto:legal@cosmictasha.com"
              className="text-ct-accent hover:underline"
            >
              legal@cosmictasha.com
            </a>
            .
          </p>
        </div>
      </section>

      <div className="mt-16">
        <Link
          href="/"
          className="text-sm text-ct-accent hover:underline"
        >
          &larr; Back to home
        </Link>
      </div>
    </main>
  );
}
