"use client";

import { markdownToHtml } from "./markdown-to-html";

/**
 * Export document sections as a print-optimized PDF via browser print dialog.
 * Opens a styled HTML document in a new window and triggers `window.print()`.
 */
export function exportToPdf(
  documentName: string,
  sections: { title: string; content: string }[],
): void {
  const date = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const sectionHtml = sections
    .map(
      (s) => `
      <section>
        <h1>${escapeHtml(s.title)}</h1>
        ${markdownToHtml(s.content)}
      </section>`,
    )
    .join("\n");

  const html = buildPrintHtml(documentName, date, sectionHtml);

  const blob = new Blob([html], { type: "text/html;charset=utf-8" });
  const url = URL.createObjectURL(blob);

  const printWindow = window.open(url, "_blank");
  if (!printWindow) {
    URL.revokeObjectURL(url);
    alert("Please allow pop-ups to export as PDF.");
    return;
  }

  // Wait for content to render before triggering print
  printWindow.addEventListener("load", () => {
    printWindow.focus();
    printWindow.print();
    // Clean up blob URL after a delay to let print dialog work
    setTimeout(() => URL.revokeObjectURL(url), 60_000);
  });
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function buildPrintHtml(
  documentName: string,
  date: string,
  sectionHtml: string,
): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>${escapeHtml(documentName)}</title>
  <style>
    @page {
      margin: 2cm;
      size: letter;
    }

    *, *::before, *::after {
      box-sizing: border-box;
    }

    body {
      font-family: Georgia, "Times New Roman", Times, serif;
      font-size: 12pt;
      line-height: 1.6;
      color: #1a1a1a;
      background: white;
      margin: 0;
      padding: 0;
    }

    h1, h2, h3 {
      font-family: system-ui, -apple-system, "Segoe UI", Roboto, sans-serif;
      color: #111;
      margin-top: 1.5em;
      margin-bottom: 0.5em;
    }

    h1 {
      font-size: 20pt;
      border-bottom: 2px solid #e5e7eb;
      padding-bottom: 0.3em;
      page-break-before: always;
    }

    /* Don't page-break before the first H1 in the document body */
    section:first-child h1 {
      page-break-before: avoid;
    }

    h2 {
      font-size: 16pt;
    }

    h3 {
      font-size: 13pt;
    }

    p {
      margin: 0.6em 0;
    }

    ul, ol {
      margin: 0.6em 0;
      padding-left: 2em;
    }

    li {
      margin: 0.3em 0;
    }

    table {
      width: 100%;
      border-collapse: collapse;
      margin: 1em 0;
      font-size: 11pt;
    }

    th, td {
      border: 1px solid #d1d5db;
      padding: 8px 12px;
      text-align: left;
    }

    th {
      background: #f3f4f6;
      font-family: system-ui, -apple-system, "Segoe UI", Roboto, sans-serif;
      font-weight: 600;
      font-size: 10pt;
      text-transform: uppercase;
      letter-spacing: 0.03em;
    }

    tr:nth-child(even) td {
      background: #f9fafb;
    }

    strong {
      font-weight: 700;
    }

    em {
      font-style: italic;
    }

    /* Title page */
    .title-page {
      text-align: center;
      padding-top: 30vh;
      page-break-after: always;
    }

    .title-page h1 {
      font-size: 28pt;
      border: none;
      page-break-before: avoid;
    }

    .title-page .meta {
      margin-top: 2em;
      font-size: 11pt;
      color: #6b7280;
    }

    /* Footer */
    .footer {
      position: fixed;
      bottom: 0;
      left: 0;
      right: 0;
      text-align: center;
      font-size: 8pt;
      color: #9ca3af;
      font-family: system-ui, -apple-system, "Segoe UI", Roboto, sans-serif;
      padding-bottom: 0.5cm;
    }

    @media print {
      .no-print { display: none !important; }
    }
  </style>
</head>
<body>
  <div class="title-page">
    <h1>${escapeHtml(documentName)}</h1>
    <div class="meta">
      <p>Generated by CosmicTasha</p>
      <p>${date}</p>
    </div>
  </div>

  ${sectionHtml}

  <div class="footer">
    Generated by CosmicTasha &bull; ${date}
  </div>
</body>
</html>`;
}
